### PR TITLE
Lessen contrast of empty area of tabline

### PR DESCRIPTION
**Pull request by JakobGM**
Hi!

This is just my subjective opinion, of course, but I find the light color currently used in the empty part of the tabline is a bit too bright.

I will fork the project for myself if you do not agree ;)

Thanks in advance, whatever you decide,
Jakob

PS: Thanks for the great work!

### CODE REVIEW

**Comment by JakobGM** [comment]
**After**:
screenshot 2017-11-14 22 30 10

**Comment by JakobGM** [comment]
**Before**:
screenshot 2017-11-14 22 49 09

**Comment by JakobGM** [comment]
If it is of interest...

I have used these plugins:
```
Plug 'itchyny/lightline.vim'                                            " Lightweight statusline without slow plugin integrations
Plug 'shinchu/lightline-gruvbox.vim'                                    " Gruvbox theme for the lightline statusline
Plug 'taohex/lightline-buffer'                                          " Buffer-bar plugin for lightline
Plug 'edkolev/tmuxline.vim'                                             " Colortheme for tmux powerline, using vim colorschemes
```

Where the last one has been used in order to "port" your colorscheme to tmux.

**Comment by shinchu** [comment]
Thank you so much for your contribution!
I think your modification is great.
I myself, however, would rather be stick with the original version for the time being...

Although I'm closing the pull request, I also want to thank you for your fork.
Anyone can use your version of `lightline-gruvbox.vim` now!

**Pull request closed without merging**
